import { Component } from '@angular/core';

import {
  Vehicle,
  TimeFrame,
} from './../../../models';
import { TimeFramedStatsComponent } from './../time-framed-stats/time-framed-stats.component';

@Component({
  selector: 'nb-most-booked-vehicles',
  templateUrl: './most-booked-vehicles.component.html',
  styleUrls: ['./most-booked-vehicles.component.css']
})
export class MostBookedVehiclesComponent extends TimeFramedStatsComponent {

  vehicles: Vehicle[];

  private table: any;

  protected fetchData() {
    this.vehicles = [];
    this.getVehicles();
  }

  private buildTable() {
    const table: any = $('#most-booked-vehicles-datatable');
    if (!table) {
      const err = this.lang.get('err_failed_finding_datatable_v');
      return this.notificationService.notifyError(err);
    }

    const settings: Object = {
      pagingType: 'full_numbers',
      retrieve: true,
      order: [[2, 'desc']],
      columnDefs: [
        { targets: [0, 1], sortable: false, searchable: false }
      ]
    };

    setTimeout(() => {
      this.table = table.DataTable(<DataTables.Settings>settings);
    });
  }

  getVehicles() {
    this.isBusy = true;
    this.subscription = this.statsService.getMostBookedVehicles(this.timeFrame)
      .subscribe(
        data => {
          this.isBusy = false;
          this.vehicles = data;

          if (this.vehicles.length === 0) {
            return;
          }

          if (!this.table) {
            this.buildTable();
          } else if (this.table) {
            // make DataTable register new vehicles
            // by making it to "rerender" the rows generated by Angular2
            setTimeout(() => {
              const tbody = this.table.table().body();
              this.table
                .clear()
                .rows.add(jQuery(tbody).children('tr'))
                .draw()
              ;
            });
          }
        },
        err => {
          this.isBusy = false;
          this.notificationService.notifyError(this.lang.get('err_failed_fetching_vehicles'));
        }
      )
    ;
  }
}
